<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose.                                                    Admin                                                    Analyst                                                    Reviewer</name>
   <tag></tag>
   <elementGuidId>d638116f-adc4-49d9-8648-2e3cc862df34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ddlRole']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ddlRole</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ddlRole</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0fb8001e-03b7-4723-af25-140131915fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d6e7d2b5-cbeb-4949-90a2-06d6c818df52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ddlRole</value>
      <webElementGuid>13ad714d-7d71-4b30-a442-77b423562f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserData.CDRole</value>
      <webElementGuid>6d065fee-bbbd-40ca-b515-e3780aa851c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Choose...
                                                    Admin
                                                    Analyst
                                                    Reviewer
                                                    Approver
                                                    Admin 4
                                                    Admin6
                                                    Manager
                                                    User
                                                    Test Demo
                                                    Test Demo1
                                            </value>
      <webElementGuid>de00a2b8-e81f-4494-a3a7-1f0b2ef4c3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ddlRole&quot;)</value>
      <webElementGuid>e6528722-6fdc-42d9-8018-d07da3e9c78c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ddlRole']</value>
      <webElementGuid>a2db10b1-05a4-4ed1-8772-b757a58caf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/fieldset/div[3]/div/select</value>
      <webElementGuid>0a2a5902-e31d-4114-b67b-612e444c274e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIGN IN'])[1]/preceding::select[1]</value>
      <webElementGuid>bfb7dfb9-abee-489f-9ccf-57c4d2817baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4a73a2fe-49dd-46ac-95e4-783d51e90391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ddlRole' and @name = 'UserData.CDRole' and (text() = '
                                                Choose...
                                                    Admin
                                                    Analyst
                                                    Reviewer
                                                    Approver
                                                    Admin 4
                                                    Admin6
                                                    Manager
                                                    User
                                                    Test Demo
                                                    Test Demo1
                                            ' or . = '
                                                Choose...
                                                    Admin
                                                    Analyst
                                                    Reviewer
                                                    Approver
                                                    Admin 4
                                                    Admin6
                                                    Manager
                                                    User
                                                    Test Demo
                                                    Test Demo1
                                            ')]</value>
      <webElementGuid>63756690-a642-48b2-a395-d71d9a45f023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
