<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hi Welcome Umar Farook</name>
   <tag></tag>
   <elementGuidId>0e7db7c9-9994-4fac-96fe-03e7e95c27d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UserDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;! Hi Welcome Umar Farook&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa56620d-bcb4-4211-94e4-446c7afe3666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88764983-5c00-4c1c-96e3-dddd71e282f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserDropdown</value>
      <webElementGuid>35ebc427-bf46-4679-8010-61cf6914e8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>04ff6d11-3b0d-4f76-8d38-635e32c21dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa1861d7-48fc-40c0-ad1c-9b7bf48e7872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>! Hi Welcome Umar Farook</value>
      <webElementGuid>7b94219b-186d-4c4b-b527-7e22c23c5bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserDropdown&quot;)</value>
      <webElementGuid>7f579cd5-c182-4f08-8a7c-1d09bdb62c9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='UserDropdown']</value>
      <webElementGuid>2591771b-5103-4739-8dfa-3d458788da0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'! Hi Welcome Umar Farook')]</value>
      <webElementGuid>bdf38864-3cbc-498d-a9db-04faeb3de343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::a[1]</value>
      <webElementGuid>e4e48911-d1e1-495e-95ac-ae012279bf5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electrode Log'])[1]/preceding::a[3]</value>
      <webElementGuid>60a4b4cc-354b-4a92-ae70-973bc05e04d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='! Hi Welcome Umar Farook']/parent::*</value>
      <webElementGuid>e1a566f2-1871-4cf5-a33a-0179ef777326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>96a42afe-4385-4efd-b8b6-c4685bdf2586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'UserDropdown' and (text() = '! Hi Welcome Umar Farook' or . = '! Hi Welcome Umar Farook')]</value>
      <webElementGuid>2c6ec3a2-bdc2-458b-9403-13d6c86b7504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
