<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hi Welcome Umar Farook</name>
   <tag></tag>
   <elementGuidId>2085e6eb-a1ba-4dd4-932e-995a647397fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='UserDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;! Hi Welcome Umar Farook&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5bfbee68-e1e9-41ef-a0e7-b0dcbac2d920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>efd79ed9-61a3-4493-8891-5026f61cd53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserDropdown</value>
      <webElementGuid>84472709-493c-4f50-82cb-15379332856d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>980cdbdd-b050-4787-b136-5192d9d03736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5cc7aa2c-c644-491b-bc52-e7ef018e6c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>! Hi Welcome Umar Farook</value>
      <webElementGuid>011f21c3-affe-4340-a898-1028e5025736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserDropdown&quot;)</value>
      <webElementGuid>d81421ea-9d27-4cc7-acf6-f10cd919bf96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='UserDropdown']</value>
      <webElementGuid>5be42730-2634-4742-9019-b17600435723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'! Hi Welcome Umar Farook')]</value>
      <webElementGuid>b1cb39da-3307-496e-93b1-8c8358d5504d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::a[1]</value>
      <webElementGuid>515b07db-93da-4b6c-beb1-45b1a310cb7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Management'])[1]/preceding::a[3]</value>
      <webElementGuid>19ff6b19-8ed5-4832-bd5a-acb606bb8473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='! Hi Welcome Umar Farook']/parent::*</value>
      <webElementGuid>9e5c3287-ba51-453a-99b5-e8a3a0039713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>b0ee33d6-0ad9-4bf9-b71f-483384c6a2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'UserDropdown' and (text() = '! Hi Welcome Umar Farook' or . = '! Hi Welcome Umar Farook')]</value>
      <webElementGuid>fe4d6d71-b008-46a9-acde-718df16ea53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
