<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SIGN IN_UserData.UserID</name>
   <tag></tag>
   <elementGuidId>f34ad906-365d-415e-9eef-ed797c6802ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUserID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUserID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Username&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef09c416-ebb1-4a01-9594-5c1f91269319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2c4b641-6b97-4ba6-a79d-ab245a468b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>678774cd-516c-4859-9812-9f727bc3928f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserID</value>
      <webElementGuid>58ee6eb7-7a98-4743-840a-23e99d71a60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>bd4c1bac-92d7-4a24-ab8a-1fd0d97af57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserData.UserID</value>
      <webElementGuid>ead233a7-f8e2-4640-bb1a-74a3eb60e2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUserID&quot;)</value>
      <webElementGuid>a55ab0d4-76b9-48cf-a565-85dbe6476912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUserID']</value>
      <webElementGuid>a37c4ef2-e4e9-4ca0-9ec4-eac7770ee722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/fieldset/div/div/input[2]</value>
      <webElementGuid>3413f988-5234-4532-8ee3-4596a764fb89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>e8f2a8d2-e971-430c-8a82-3bf733593848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtUserID' and @placeholder = 'Username' and @name = 'UserData.UserID']</value>
      <webElementGuid>3d550a25-b72d-495f-be9c-89702ef5bc4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
