<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>575d9704-3f7d-4dcc-aaec-044637a6521d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UM > figure > a > img[alt=&quot;image&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UM']/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#UM >> internal:role=link[name=&quot;image&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ca41f464-866f-433b-8623-94cb77016dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/productlogos/user managementNew.png</value>
      <webElementGuid>0f639c30-178c-4ae6-b6a0-c45c9e9c07ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>0790fa45-d8b1-4fae-b855-4e854272b484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UM&quot;)/figure[1]/a[1]/img[1]</value>
      <webElementGuid>8f70e736-de9f-4bd6-b4d9-7ebe9ead00dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UM']/figure/a/img</value>
      <webElementGuid>19484353-a5ac-4b3e-adc0-232228522df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='image'])[16]</value>
      <webElementGuid>ad908646-740f-4348-b3f8-8b96677f76c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/figure/a/img</value>
      <webElementGuid>fb1a6567-9a29-43f8-b8b7-8ff517bc0650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/productlogos/user managementNew.png' and @alt = 'image']</value>
      <webElementGuid>ca7abb6f-18bf-4de7-9e0d-17f06c5ce92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
