<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3a2f1745-96b0-4e89-8c95-17d148fbe21e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EL > figure > a > img[alt=&quot;image&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EL']/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#EL >> internal:role=link[name=&quot;image&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a649fbf-46f8-4018-9312-12565530eeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/productlogos/Electrod.png</value>
      <webElementGuid>3a13020b-8a14-4178-9ee2-977838b822e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>bdbff365-6f03-4266-a371-a65b555f1ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EL&quot;)/figure[1]/a[1]/img[1]</value>
      <webElementGuid>b534e906-56cc-4636-901f-cdfc3ecf3763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EL']/figure/a/img</value>
      <webElementGuid>54a20841-480c-473f-b843-f1ea29d07bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='image'])[11]</value>
      <webElementGuid>c8db3f28-b42e-4635-a951-3c0b6c867694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/figure/a/img</value>
      <webElementGuid>e2c30dc2-7d07-4fe4-8273-a200f6b254e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/productlogos/Electrod.png' and @alt = 'image']</value>
      <webElementGuid>49706b97-de7c-4cac-8d57-eb92390edc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
